monitor.alsa.rules = [
  # HyperX Cloud 3 wireless
  #-----------------------------------------------------------------------------
  {
    matches = [
      { node.name = "alsa_output.usb-HP__Inc_HyperX_Cloud_III_Wireless_0000000000000000-00.analog-stereo" }
    ]
    actions = {
      update-props = {
        priority.driver  = 1010
        priority.session = 1010
      }
    }
  }
  # Iiyama builtin speakers
  #-----------------------------------------------------------------------------
  {
    matches = [
      { node.name = "alsa_output.pci-0000_03_00.1.hdmi-stereo" }
    ]
    actions = {
      update-props = {
        priority.driver  = 1020
        priority.session = 1020
      }
    }
  }
  # Nothing Ear (a)
  #-----------------------------------------------------------------------------
  {
    matches = [
      { node.name = "bluez_output.3C_B0_ED_B0_BA_F6.1" }
    ]
    actions = {
      update-props = {
        priority.driver  = 1030
        priority.session = 1030
      }
    }
  }
  # Bose QuietComfort Ultra
  #-----------------------------------------------------------------------------
  {
    matches = [
      { node.name = "bluez_output_internal.BC_87_FA_99_B8_C4.1" }
    ]
    actions = {
      update-props = {
        priority.driver  = 1040
        priority.session = 1040
      }
    }
  }
]
