<%
    if DEPLOY_HOST == 'casino':
        terminal_font_size = font_size_medium
    else:
        terminal_font_size = font_size_msmall
%>
#-------------------------------------------------------------------------------
# Alacritty configuration file
#-------------------------------------------------------------------------------

# Environment
#-------------------------------------------------------------------------------

[env]
COLORTERM = 'truecolor'

# Appearance
#-------------------------------------------------------------------------------

[bell]
animation = 'Linear'
color = '${color_zerox('black')}'
duration = 100

[cursor.style]
blinking = 'Off'
shape = 'Block'

[font]
size = ${terminal_font_size}

[font.normal]
family = '${font_mono}'
style = 'Regular'

[window]
opacity = 0.8
% if DEPLOY_DISTRO == 'ubuntu':
decorations = 'none'
% endif

[window.padding]
x = 0
y = 0

# Key bindings
#
# Example breakdown of CSIu Ctrl+Shift+C:
#   \u001b\u005b\u0063\u003b\u0035\u0075
#
#   - Control sequence introducer (CSI) is \u001b\u005b
#   - Character c is \u0063
#   - Separator ; is \u003b
#   - Modifiers bitflag* for Ctrl+Shift (5) is \u0035
#   - Unicode u is \u0075
#
# *Modifiers bitflag: 1 is shift, 2 is alt, 4 is ctrl
#
# For additional terminal key codes
#   see: https://aperiodic.net/pip/archives/Geekery/term-function-keys/
#-------------------------------------------------------------------------------

#------------------------------ Spawn
[[keyboard.bindings]]
mods = 'Control'
key = 'T'
action = 'SpawnNewInstance'

#------------------------------ Clipboard
# NOTE: Not working in less pager :(
[[keyboard.bindings]]
mode = '~Alt'
mods = 'Control'
key = 'C'
action = 'Copy'

[[keyboard.bindings]]
mods = 'Control'
key = 'V'
action = 'Paste'

#------------------------------ Scrolling
[[keyboard.bindings]]
mode = '~Alt'
key = 'PageDown'
action = 'ScrollHalfPageDown'

[[keyboard.bindings]]
mode = '~Alt'
key = 'PageUp'
action = 'ScrollHalfPageUp'

[[keyboard.bindings]]
mode = '~Alt'
mods = 'Shift'
key = 'Down'
action = 'ScrollLineDown'

[[keyboard.bindings]]
mode = '~Alt'
mods = 'Shift'
key = 'Up'
action = 'ScrollLineUp'

#------------------------------ Signals
# STTY interrupt passthrough
[[keyboard.bindings]]
mods = 'Control'
key = 'X'
chars = "\u0003"

#------------------------------ Passthrough
# Ctrl+I -> F16 passthrough
[[keyboard.bindings]]
mods = 'Control'
key = 'I'
chars = "\u001b\u005b\u0031\u003b\u0032\u0053"

# Ctrl+M -> F17 passthrough
[[keyboard.bindings]]
mods = 'Control'
key = 'M'
chars = "\u001b\u005b\u0031\u0035\u003b\u0032\u007e"

# Ctrl+Backspace -> F18 passthrough
[[keyboard.bindings]]
mods = 'Control'
key = 'Backspace'
chars = "\u001b\u005b\u0031\u0037\u003b\u0032\u007e"

# Ctrl+Period -> F19 passthrough
[[keyboard.bindings]]
mods = 'Control'
key = 'Period'
chars = "\u001b\u005b\u0031\u0038\u003b\u0032\u007e"

# Ctrl+Tab passthrough (NVIM can correctly interpret this, no function key hack)
[[keyboard.bindings]]
mods = 'Control'
key = 'Tab'
chars = "\u001b\u005b\u0039\u003b\u0035\u0075"

# Ctrl+Semicolon -> F20 passthrough
[[keyboard.bindings]]
mods = 'Control'
key = 'Semicolon'
chars = "\u001b\u005b\u0031\u0039\u003b\u0032\u007e"

# Colors
#-------------------------------------------------------------------------------

[colors]
draw_bold_text_with_bright_colors = false

[colors.selection]
text = '${color_zerox('selection_fg')}'
background = '${color_zerox('selection_bg')}'

[colors.primary]
background = '${color_zerox('terminal_bg')}'
foreground = '${color_zerox('terminal_text')}'

[colors.cursor]
cursor = '${color_zerox('terminal_text')}'
text = '${color_zerox('terminal_bg')}'

[colors.normal]
black = '${color_zerox('ansi_black')}'
red = '${color_zerox('ansi_red')}'
green = '${color_zerox('ansi_green')}'
yellow = '${color_zerox('ansi_yellow')}'
blue = '${color_zerox('ansi_blue')}'
magenta = '${color_zerox('ansi_magenta')}'
cyan = '${color_zerox('ansi_cyan')}'
white = '${color_zerox('ansi_white')}'

[colors.bright]
black = '${color_zerox('ansi_brblack')}'
red = '${color_zerox('ansi_brred')}'
green = '${color_zerox('ansi_brgreen')}'
yellow = '${color_zerox('ansi_bryellow')}'
blue = '${color_zerox('ansi_brblue')}'
magenta = '${color_zerox('ansi_brmagenta')}'
cyan = '${color_zerox('ansi_brcyan')}'
white = '${color_zerox('ansi_brwhite')}'

<%
indexed_colors = []
idx = 16
for name, count in [
    ('primary', 16), ('secondary', 16), ('text', 16), ('gray', 16),
    ('red', 10), ('orange', 10), ('yellow', 10), ('green', 10),
    ('cyan', 10), ('blue', 10), ('purple', 10), ('magenta', 10),
]:
    for i in range(count):
        indexed_colors.append((idx, f'{name}_{i}'))
        idx += 1
%>
% for index, key in indexed_colors:
[[colors.indexed_colors]]
color = '${color_zerox(key)}'
index = ${index}

% endfor
