#!/usr/bin/env bash
#-------------------------------------------------------------------------------
# River configuration script
#
# See the river(1), riverctl(1), and rivercarro(1) man pages for complete
# documentation.
#-------------------------------------------------------------------------------

declare config_dir=${XDG_CONFIG_HOME:-$HOME/.config}
declare scripts_dir=${XDG_SCRIPTS_HOME:-$HOME/.local/scripts}
declare opt_dir=${XDG_OPT_HOME:-$HOME/.local/opt}

# Imports
#-------------------------------------------------------------------------------

# shellcheck disable=SC1091
source "$opt_dir/theme/theme.sh"

# shellcheck disable=SC1091
source "$opt_dir/shell-utils/debug.sh"

# Validation
#-------------------------------------------------------------------------------

assert_dependency way-displays

# Systemd integration
# TODO: This should be part of the river/systemd integration.
#-------------------------------------------------------------------------------

systemd-cat --identifier=river echo "Initializing River..."

# Share part of river environment with systemd.
# NOTE: `spawn` is necessary, or this won't work.
systemd_variables="XDG_CURRENT_DESKTOP XDG_SESSION_TYPE WAYLAND_DISPLAY"
riverctl spawn "dbus-update-activation-environment --systemd $systemd_variables"

# Other system services can interact with the underlying wayland-session or
# graphical-session.target.
systemctl --user start river-session.target

# Input configuration
#-------------------------------------------------------------------------------

riverctl focus-follows-cursor normal

# Keyboard repeat rate
riverctl set-repeat 50 300

# Hide inactive cursor
riverctl hide-cursor timeout 3000

# Mouse sensitivity
riverctl input pointer-1189-32769-BenQ_ZOWIE_BenQ_ZOWIE_Gaming_Mouse accel-profile flat
riverctl input pointer-1189-32769-BenQ_ZOWIE_BenQ_ZOWIE_Gaming_Mouse accel-speed -0.7

# Layout generator
#-------------------------------------------------------------------------------

riverctl default-layout rivercarro
riverctl spawn "rivercarro -inner-gaps 6 -outer-gaps 0 -main-ratio 0.65 -main-location right"

# Adjust screen brightness
#-------------------------------------------------------------------------------

# NOTE: Experiment with both.
# riverctl spawn "gammastep -l 52.155472:5.389358"
riverctl spawn "wlsunset -l 52.155472 -L 5.389358"

# Display management
#-------------------------------------------------------------------------------

way-displays > "/tmp/way-displays.${XDG_VTNR}.${USER}.log" 2>&1 &

# NOTE: Way-displays needs a moment.
sleep 0.25

# Theme
#-------------------------------------------------------------------------------

# shellcheck disable=SC1091
source "$config_dir/river/theme.sh"

# Workspace
#-------------------------------------------------------------------------------

# shellcheck disable=SC1091
source "$config_dir/river/workspace.sh"

# App configuration
#-------------------------------------------------------------------------------

# Floating windows
riverctl rule-add -app-id floating float
riverctl rule-add -app-id yad float
riverctl rule-add -app-id xdg-desktop-portal-gtk float

# Override client-side decorations
riverctl rule-add -app-id marker ssd
riverctl rule-add -app-id nm-connection-editor ssd
riverctl rule-add -app-id nwg-look ssd
riverctl rule-add -app-id gtk-pipe-viewer ssd
riverctl rule-add -app-id org.pulseaudio.pavucontrol ssd
riverctl rule-add -title Transmission ssd
riverctl rule-add -app-id yad ssd
riverctl rule-add -app-id yad-settings ssd
riverctl rule-add -app-id org.pwmt.zathura ssd

# Key mappings
#-------------------------------------------------------------------------------

# shellcheck disable=SC1091
source "$config_dir/river/keymaps.sh"

# Clean home
#-------------------------------------------------------------------------------

"$scripts_dir/clean-home.sh"

# Systemd integration
#-------------------------------------------------------------------------------

systemd-cat --identifier=river echo "River initialized."

# Clean up the shared environment when river is interrupted or terminated.
session_cleanup () {
    systemd-cat --identifier=river echo "Cleaning River."

    systemctl --user unset-environment "$systemd_variables"

    exit
}

trap session_cleanup INT TERM

# NOTE: The assumption is: if WAYLAND_DISPLAY is in use, river is running.
while [ -n "$WAYLAND_DISPLAY" ]
do
    sleep 1.00
done
