#!/usr/bin/env bash
#-------------------------------------------------------------------------------
# River configuration script
#
# See the river(1), riverctl(1), and rivercarro(1) man pages for complete
# documentation.
#-------------------------------------------------------------------------------

declare config_dir=${XDG_CONFIG_HOME:-$HOME/.config}
declare opt_dir=${XDG_OPT_HOME:-$HOME/.local/opt}

# Imports
#-------------------------------------------------------------------------------

# shellcheck disable=SC1091
source "$opt_dir/theme/theme.sh"

# shellcheck disable=SC1091
source "$opt_dir/shell-utils/debug.sh"

# Validation
#-------------------------------------------------------------------------------

assert_dependency way-displays

# Systemd integration
# TODO: This should be part of the river/systemd integration.
#-------------------------------------------------------------------------------

systemd-cat --identifier=river echo "Initializing River..."

# Share part of river environment with systemd.
# NOTE: `spawn` is necessary, or this won't work.
systemd_variables="XDG_CURRENT_DESKTOP XDG_SESSION_TYPE WAYLAND_DISPLAY"
riverctl spawn "dbus-update-activation-environment --systemd $systemd_variables"

# Other system services can respond to the underlying wayland-session or graphical-session.target.
systemctl --user start river-session.target

# Input configuration
#-------------------------------------------------------------------------------

riverctl focus-follows-cursor normal

# Keyboard repeat rate
riverctl set-repeat 50 300

# Mouse configuration
riverctl input pointer-1133-49309-Logitech_G203_LIGHTSYNC_Gaming_Mouse accel-profile flat
riverctl input pointer-1133-49309-Logitech_G203_LIGHTSYNC_Gaming_Mouse pointer-accel 1.0

# Hide inactive cursor
riverctl hide-cursor timeout 3000

# Styling
#-------------------------------------------------------------------------------

# shellcheck disable=SC2154
riverctl background-color "$(color_zerox "$system_bg")"
# shellcheck disable=SC2154
riverctl border-color-focused "$(color_zerox "$primary_8")"
# shellcheck disable=SC2154
riverctl border-color-unfocused "$(color_zerox "$primary_3")"
# shellcheck disable=SC2154
riverctl border-color-urgent "$(color_zerox "$red_4")"

riverctl border-width 3

# shellcheck disable=SC2154
riverctl xcursor-theme "$cursor_theme" "$cursor_size"

# Layout generator
#-------------------------------------------------------------------------------

riverctl default-layout rivercarro
riverctl spawn "rivercarro -inner-gaps 6 -outer-gaps 0 -main-ratio 0.65 -main-location right"

# Display management
#-------------------------------------------------------------------------------

way-displays > "/tmp/way-displays.${XDG_VTNR}.${USER}.log" 2>&1 &

# NOTE: Way-displays needs a moment.
sleep 0.25

# Wallpaper
#-------------------------------------------------------------------------------

# shellcheck disable=SC1091
source "$config_dir/wallpaper/wallpaper.sh"

# Workspace
#-------------------------------------------------------------------------------

# shellcheck disable=SC1091
source "$config_dir/river/workspace.sh"

# Status bar
#-------------------------------------------------------------------------------

riverctl spawn waybar

# App configuration
#-------------------------------------------------------------------------------

# Floating windows
riverctl rule-add -app-id yad float
riverctl rule-add -app-id xdg-desktop-portal-gtk float

# Override client-side decorations
riverctl rule-add -app-id marker ssd
riverctl rule-add -app-id nm-connection-editor ssd
riverctl rule-add -app-id nwg-look ssd
riverctl rule-add -app-id gtk-pipe-viewer ssd
riverctl rule-add -app-id pavucontrol ssd
riverctl rule-add -app-id transmission ssd
riverctl rule-add -app-id yad ssd
riverctl rule-add -app-id yad-settings ssd
# NOTE: Seems to have no effect.
riverctl rule-add -app-id zathura ssd

# Key mappings
#-------------------------------------------------------------------------------

# shellcheck disable=SC1091
source "$config_dir/river/keymaps.sh"

# Systemd integration
#-------------------------------------------------------------------------------

systemd-cat --identifier=river echo "River initialized."

# Clean up the shared environment when river is interrupted or terminated.
session_cleanup () {
    pkill -x waybar
    pkill -x way-displays

    systemd-cat --identifier=river echo "Cleaning River."

    systemctl --user unset-environment "$systemd_variables"

    exit
}

trap session_cleanup INT TERM

# NOTE: The assumption is: if WAYLAND_DISPLAY is in use, river is running.
while [ -n "$WAYLAND_DISPLAY" ]
do
    sleep 0.10
done
