#-------------------------------------------------------------------------------
# Direnv configuration file
#-------------------------------------------------------------------------------

[global]
log_filter="^$"
