# Workspace session for the Habits for Health (HfH) project.

[[entry]]
type = "browser"
workspace = "1"
workspace_name = "kanban"
session = "omnia-hfh-kanban"

[[entry]]
type = "browser"
workspace = "2"
workspace_name = "cicd"
session = "omnia-hfh-cicd"

[[entry]]
type = "terminal"
workspace = "dev"
cwd = "/home/surfer/Code/wellbeing-people-mobile-app"

[[entry]]
type = "terminal"
workspace = "dev"
cwd = "/home/surfer/Code/wellbeing-people-mobile-app"
command = "edit"

[[entry]]
type = "terminal"
workspace = "project"
cwd = "/home/surfer/Documents/work/codemuch/clients/omnia-digital"

[[entry]]
type = "terminal"
workspace = "project"
cwd = "/home/surfer/Documents/work/codemuch/clients/omnia-digital"
command = "edit"
