#-------------------------------------------------------------------------------
# Bash aliases
#-------------------------------------------------------------------------------

# Git
alias g="git"
alias ga="git add"
alias gaa="git add -A"
alias gai="git add -i"
alias gb="git branch -v"
alias gc="git commit -m"
alias gca="git commit --amend"
alias gcl="git clone"
alias gco="git checkout"
alias gcp="git cherry-pick"
alias gd="git diff"
alias gdd="git -c delta.side-by-side=true diff"
alias gdd="git -c delta.side-by-side=true diff --staged"
alias gds="git diff --staged"
alias gl="git log --pretty=history"
alias gp="git push"
alias gpa="git push --all"
alias gpf="git push --force"
alias gpu="git pull --rebase"
alias gr="git remote -v"
alias grb="git rebase"
alias grba="git rebase --abort"
alias grbc="git rebase --continue"
alias grbi="git rebase -i"
alias grc="git rm --cached"
alias grs="git reset HEAD"
alias grt="git restore"
alias gs="git status"
alias gsh="git show"
alias gsu="git status -u"
alias gss="git switch"
alias gsc="git switch -c"
alias wip="git add -A; git commit -m '[WIP]'; git push"

# General
alias bat="bat --force-colorization --no-paging --style=grid,numbers"
alias c="clear"
alias e="edit"
alias ed="edit"
alias edi="edit"
alias eza="eza -l --color=always --group-directories-first --time-style=long-iso"
alias ez="eza"
alias lf="lfcd"
alias ls="eza"
alias lsa="eza -a"
alias lsd="eza -a"
alias lsi="eza --git-ignore"
alias lst="eza -T --git-ignore"
alias lsat="eza -aT --git-ignore"
alias lsta="eza -aT --git-ignore"
alias ip="ip -c"
alias oc="opencode"
alias rga="rg --hidden --no-ignore"
alias zz="z -"

# Python
alias vv="generate-venv.sh"
alias va="source venv/bin/activate"
alias vd="deactivate"

# Docker
alias d="docker"
alias dc="docker compose"
alias dcu="docker compose up"
alias dcd="docker compose down"
alias dps="docker ps | view"
alias dv="docker volume"
alias dss="docker stop \$(docker ps -q)"
