#!/bin/sh

# https://cssgradient.io/

# Theme
#-------------------------------------------------------------------------------

# Special
debug='#ff00ff'

# Primary: 16-31
 primary_0='#000610'
 primary_1='#000d1e'
 primary_2='#00152d'
 primary_3='#011d3c'
 primary_4='#01244b'
 primary_5='#022c5a'
 primary_6='#023469'
 primary_7='#023b78'
 primary_8='#034387'
 primary_9='#034b96'
primary_10='#055eb5'
primary_11='#056dc4'
primary_12='#057cd3'
primary_13='#058be1'
primary_14='#059af0'
primary_15='#05aaff'

# Secondary: 32-47
 secondary_0='#000e14'
 secondary_1='#02151d'
 secondary_2='#041d27'
 secondary_3='#062431'
 secondary_4='#082c3b'
 secondary_5='#0a3344'
 secondary_6='#0c3b4e'
 secondary_7='#0e4e65'
 secondary_8='#0d5d74'
 secondary_9='#0c6c84'
secondary_10='#0b7b93'
secondary_11='#0a8aa2'
secondary_12='#0999b1'
secondary_13='#08a8c0'
secondary_14='#07b7cf'
secondary_15='#06c6df'

# Text: 48-63
 text_0='#001020'
 text_1='#0e1e2e'
 text_2='#1d2d3d'
 text_3='#2c3c4c'
 text_4='#3b4b5b'
 text_5='#4a5a6a'
 text_6='#596979'
 text_7='#687888'
 text_8='#768696'
 text_9='#8595a5'
text_10='#94a4b4'
text_11='#a3b3c3'
text_12='#b2c2d2'
text_13='#c1d1e1'
text_14='#d0e0f0'
text_15='#dfefff'

# Gray: 64-79
 gray_0='#0b0b0e'
 gray_1='#191a20'
 gray_2='#282932'
 gray_3='#363844'
 gray_4='#454757'
 gray_5='#535669'
 gray_6='#62657b'
 gray_7='#71758e'
 gray_8='#71758e'
 gray_9='#83869c'
gray_10='#9598ab'
gray_11='#a7aab9'
gray_12='#babbc8'
gray_13='#cccdd6'
gray_14='#dedfe5'
gray_15='#f1f1f4'

# Red: 80-89
red_0='#1a0200'
red_1='#4d0500'
red_2='#800900'
red_3='#b30c00'
red_4='#cc0e00'
red_5='#e60f00'
red_6='#ff291a'
red_7='#ff584d'
red_8='#ff8880'
red_9='#ffb8b3'

# Orange: 90-99
orange_0='#1a0f00'
orange_1='#331f00'
orange_2='#663d00'
orange_3='#995c00'
orange_4='#ff9500'
orange_5='#ff9900'
orange_6='#ffad33'
orange_7='#ffc266'
orange_8='#ffd699'
orange_9='#ffebcc'

# Yellow: 100-109
yellow_0='#332a00'
yellow_1='#665300'
yellow_2='#997d00'
yellow_3='#cca700'
yellow_4='#ffd000'
yellow_5='#ffda33'
yellow_6='#ffde4d'
yellow_7='#ffe880'
yellow_8='#fff1b3'
yellow_9='#fffae6'

# Green: 110-119
green_0='#001a0f'
green_1='#00331f'
green_2='#00663d'
green_3='#00995c'
green_4='#00cc7a'
green_5='#00e68a'
green_6='#1affa3'
green_7='#4dffb8'
green_8='#80ffcc'
green_9='#b3ffe0'

# Cyan: 120-129
cyan_0='#00131a'
cyan_1='#00384d'
cyan_2='#005e80'
cyan_3='#0083b3'
cyan_4='#00a8e6'
cyan_5='#00bbff'
cyan_6='#33c9ff'
cyan_7='#66d6ff'
cyan_8='#99e4ff'
cyan_9='#ccf1ff'

# Blue: 130-139
blue_0='#00061a'
blue_1='#000d33'
blue_2='#001a66'
blue_3='#002699'
blue_4='#0033cc'
blue_5='#003fff'
blue_6='#3366ff'
blue_7='#668cff'
blue_8='#99b3ff'
blue_9='#ccd9ff'

# Purple: 140-149
purple_0='#0e001a'
purple_1='#1d0033'
purple_2='#3a0066'
purple_3='#570099'
purple_4='#7400cc'
purple_5='#9200ff'
purple_6='#a733ff'
purple_7='#bd66ff'
purple_8='#d399ff'
purple_9='#e9ccff'

# Magenta: 150-159
magenta_0='#1a000a'
magenta_1='#330014'
magenta_2='#660029'
magenta_3='#99003d'
magenta_4='#cc0052'
magenta_5='#ff0066'
magenta_6='#ff3385'
magenta_7='#ff66a3'
magenta_8='#ff99c2'
magenta_9='#ffcce0'

# 16 indexed colors
i0=$gray_0
i1=$red_4
i2=$green_3
i3=$orange_6
i4=$primary_10
i5=$magenta_4
i6=$secondary_10
i7=$text_13
i8=$text_10
i9=$red_6
i10=$green_5
i11=$yellow_6
i12=$primary_15
i13=$magenta_6
i14=$secondary_15
i15=$text_15

# ANSI named shortcuts
ansi_black=$i0
ansi_red=$i1
ansi_green=$i2
ansi_yellow=$i3
ansi_blue=$i4
ansi_magenta=$i5
ansi_cyan=$i6
ansi_white=$i7
ansi_brblack=$i8
ansi_brred=$i9
ansi_brgreen=$i10
ansi_bryellow=$i11
ansi_brblue=$i12
ansi_brmagenta=$i13
ansi_brcyan=$i14
ansi_brwhite=$i15

# Themed
system_bg=$gray_0
system_text=$text_15

terminal_bg=$gray_0
terminal_text=$text_15

editor_bg=$gray_0
editor_text_normal=$secondary_9
