#!/usr/bin/env bash

font_mono='Iosevka NFM'
# font_mono='iosevka'
# font_mono='Hack Nerd Font Mono'
# font_mono='SauceCodePro Nerd Font'
# font_mono='Terminess Nerd Font'
# font_mono='JetBrains Mono'
# font_mono='Fira Code'

font_sans='Cantarell'
font_serif='Liberation Serif'

font_size_small=12
font_size_medium=14
font_size_large=16
