#!/usr/bin/env bash

font_mono='IosevkaTerm NFM'
font_sans='Cantarell'
font_serif='Liberation Serif'

font_size_tiny=7
font_size_xsmall=9
font_size_small=11
font_size_medium=13
font_size_large=15
font_size_xlarge=17
font_size_xxlarge=19

zoom_level=1.0
