#!/usr/bin/env bash

font_mono='IosevkaTerm'
font_sans='Liberation Sans'
font_serif='Liberation Serif'

font_size_tiny=8
font_size_xsmall=10
font_size_small=12
font_size_msmall=13
font_size_medium=14
font_size_mlarge=15
font_size_large=16
font_size_xlarge=18
font_size_xxlarge=20

zoom_level=1.10
