#!/usr/bin/env bash
#-------------------------------------------------------------------------------
# Bash profile
#-------------------------------------------------------------------------------

# Configure the bash environment.
source "$HOME/.config/bash/env.sh"

# Prevent above configuration from being run later, since we need to use
# $BASH_ENV for non-login non-interactive shells. We don't export it, as we may
# have a non-login non-interactive shell as a child.
unset BASH_ENV

source "$HOME/.config/bash/login.sh"

if [ "$PS1" ]; then
    source "$HOME/.config/bash/interactive.sh"
fi
