#!/usr/bin/env bash
#-------------------------------------------------------------------------------
# Bash interactive configuration
#-------------------------------------------------------------------------------

# If not running interactively, don't do anything.
[[ $- != *i* ]] && return

# Imports
#-------------------------------------------------------------------------------

# Generic interactive shell configuration.
source "$XDG_CONFIG_HOME/shell/interactive"

source "$XDG_SCRIPTS_HOME/string-utils.sh"

# General configuration
#-------------------------------------------------------------------------------

# Save history in an XDG compliant directory.
[[ ! -d "$DATA_DIR" ]] && mkdir -p "$DATA_DIR"
export HISTFILE="$XDG_DATA_HOME/bash/bash_history"

# GNU readline configuration.
export INPUTRC="$XDG_CONFIG_HOME/readline/config"

# Aliases
#-------------------------------------------------------------------------------

alias eza="eza -l --group-directories-first"
alias bat="bat --force-colorization --no-paging --style=grid,numbers"

alias gs="git status"
alias gsu="git status -u"
alias gl="git log --pretty='%C(yellow)[%h]%C(reset) %<(16,trunc)%ad %C(cyan)%an%C(reset) %C(green)%s%C(reset)' --date=format:'%Y-%m-%d %H:%M'"
alias gd="git diff"
alias gds="git diff --staged"
alias ga="git add"
alias gaa="git add -A"
alias gc="git commit -m"
alias gca="git commit --amend"
alias gco="git checkout"
alias gp="git push"
alias gpa="git push --all"
alias gpf="git push --force"
alias grb="git rebase -i"
alias grc="git rm --cached"
alias grv="git remote -v"
alias e="edit"
alias ed="edit"
alias edi="edit"
alias ez="eza"
alias lf="lfcd"
alias ls="eza"
alias lsa="eza -a"
alias lsi="eza --git-ignore"
alias lst="eza -T --git-ignore"
alias lst="eza -aT --git-ignore"
alias ip="ip -c"
alias vv="python -m venv venv"

# Bindings
#-------------------------------------------------------------------------------

bind '"\C-e":"edit\C-m"'
bind '"\C-f":"lfcd\C-m"'
bind '"\C-y":"clear\C-m eza -al \C-m"'

# Theme
#-------------------------------------------------------------------------------

# Import and parse system colors.
source "$XDG_CONFIG_HOME/theme/theme.sh"

# Configure directory colors (dircolors, ls).
eval "$(dircolors --bourne-shell "$XDG_CONFIG_HOME/theme/dircolors-16")"

# TODO: Implement theme function to get the terminal color code.
# Configure eza colors (based on directory colors).
export EZA_COLORS="reset:da=37:$LS_COLORS"

# LF CD integration
#-------------------------------------------------------------------------------

LFCD="$XDG_CONFIG_HOME/lf/lfcd.sh"
if [[ -f "$LFCD" ]]; then
    source "$LFCD"
fi

# Prompt
#-------------------------------------------------------------------------------

construct_prompt() {
    # Login
    local user=$(whoami)
    if [[ "$user" == "root" ]]; then
        user="\[$(color_ansi_fg $ansi_brred)\]\u\[$(color_ansi_reset)\]"
    else
        user="\[$(color_ansi_fg $ansi_brgreen)\]\u\[$(color_ansi_reset)\]"
    fi

    local separator="@" && [[ "$TERM" != "linux" ]] && separator="⋅"

    local hostname="\h"

    local login="$user$separator$hostname "

    # CWD
    local cwd="\[$(color_ansi_fg $ansi_blue)\]\w\[$(color_ansi_reset)\] "

    # Git status
    local vcs=""

    local git_symbol="" && [[ "$TERM" != "linux" ]] && git_symbol=" "

    local git_color="\[$(color_ansi_fg $ansi_green)\]"

    local git_status=$(git status 2>/dev/null | grep "Your branch is ahead" 2>/dev/null)
    if [[ -n "$git_status" ]]; then
        git_color="\[$(color_ansi_fg $ansi_yellow)\]"
    fi

    local git_status=$(git status --porcelain 2>/dev/null)
    if [[ -n "$git_status" ]]; then
        git_color="\[$(color_ansi_fg $ansi_yellow)\]"
    fi

    local git_branch=$(git branch --show-current 2>/dev/null)
    if [[ -n "$git_branch" ]]; then
        vcs="$git_color$git_symbol$git_branch\[$(color_ansi_reset)\] "
    fi

    # Python virtual environment
    local venv=""

    local venv_symbol="" && [[ "$TERM" != "linux" ]] && venv_symbol="󰌠 "

    local venv_name=""
    if [[ -n "$VIRTUAL_ENV" ]]; then
        IFS='/' read -r -a split_virtual_env <<< "$VIRTUAL_ENV"
        if string_contains "${split_virtual_env[-1]}" virtualenv venv .venv env; then
            venv_name="${split_virtual_env[-2]}"
        else
            venv_name="${split_virtual_env[-1]}"
        fi
    fi

    if [[ -n "$venv_name" ]]; then
        venv="\[$(color_ansi_fg $ansi_magenta)\]$venv_symbol$venv_name\[$(color_ansi_reset)\] "
    fi

    # Prompt
    local prompt="\[$(color_ansi_fg $text_15)\]\$\[$(color_ansi_reset)\] "

    PS1="$login$cwd$vcs$venv$prompt"
}
PROMPT_COMMAND='construct_prompt'

