#-------------------------------------------------------------------------------
# Yazi keymaps
#-------------------------------------------------------------------------------

[[manager.prepend_keymap]]
on   = "w"
run  = 'quit'
