#-------------------------------------------------------------------------------
# Yazi keymaps
#-------------------------------------------------------------------------------

[[mgr.prepend_keymap]]
on   = "l"
run  = 'plugin smart-enter'

[[mgr.prepend_keymap]]
on   = "<C-w>"
run  = 'quit'

[[mgr.prepend_keymap]]
on   = "w"
run  = 'quit --no-cwd-file'

[[mgr.prepend_keymap]]
on   = "<Esc>"
run  = 'quit'
