#-------------------------------------------------------------------------------
# Yazi keymaps
#-------------------------------------------------------------------------------

[[manager.prepend_keymap]]
on   = "w"
run  = 'quit'

[[manager.prepend_keymap]]
on   = "<C-w>"
run  = 'quit --no-cwd-file'

[[manager.prepend_keymap]]
on   = "<Esc>"
run  = 'quit'
