#-------------------------------------------------------------------------------
# Yazi theme
#-------------------------------------------------------------------------------

[manager]
syntect_theme = "~/.config/bat/themes/carbon-dark.tmTheme"
