#-------------------------------------------------------------------------------
# Yazi theme
#-------------------------------------------------------------------------------

[manager]
syntect_theme = "~/.config/bat/themes/carbon-dark.tmTheme"
border_style = { fg = "#055eb5" }
