#-------------------------------------------------------------------------------
# Yazi theme
#-------------------------------------------------------------------------------

[mgr]
syntect_theme = "~/.config/bat/themes/carbon-dark.tmTheme"
border_style = { fg = "#1d2d3d" }
