#-------------------------------------------------------------------------------
# Yazi configuration
#-------------------------------------------------------------------------------

[manager]
show_hidden = true
ratio = [1, 1, 3]
