#-------------------------------------------------------------------------------
# Yazi configuration
#-------------------------------------------------------------------------------

[manager]
show_hidden = true
ratio = [1, 1, 3]
sort_by = "natural"
sort_dir_first = true

[plugin]
prepend_previewers = [
    { mime = "application/x-tar", run = "ouch" },
    { mime = "application/x-xz", run = "ouch" },
    { mime = "application/xz", run = "ouch" },
]
